export interface ILifeCycleGateConfig {
  gateId: string;
  phase: string;
  title: string;
  checklist: string[];
}

export const LIFECYCLE_GATES_CONFIG: ILifeCycleGateConfig[] = [
  { gateId: "REG-00", phase: "A · Regulatory Setup", title: "Regulatory & Code Freeze", checklist: [
    "Planning / building authority identified",
    "TNCDBR base text and applicable amendments/Gazettes recorded",
    "Local authority circulars / approval conditions recorded",
    "NBC / IS source register prepared with edition / revision status",
    "Project-specific NOCs / special statutes identified",
  ]},
  { gateId: "CLS-01", phase: "A · Regulatory Setup", title: "Project Classification & Applicability", checklist: [
    "Occupancy / proposed use determined",
    "Height and storeys recorded",
    "High-rise / non-high-rise determination signed",
    "Residential / institutional / commercial / industrial / special occupancy triggers reviewed",
    "Road width, plot area, FSI / coverage / parking basis recorded",
    "Fire NOC, accessibility and completion/occupancy route marked Required / N.A. / Pending",
  ]},
  { gateId: "PRO-02", phase: "A · Regulatory Setup", title: "Professional Appointments & Responsibility Matrix", checklist: [
    "RA/RE appointment and registration verified",
    "RSE appointment requirement determined and verified",
    "Registered Construction Engineer requirement determined and verified",
    "Quality Auditor requirement determined and verified",
    "Geo-tech / fire / MEP / lift / plumbing specialists determined",
    "Scope, validity and project responsibility accepted in writing",
  ]},
  { gateId: "DES-03", phase: "B · Design Release", title: "Architectural & Life-Safety Design Compliance Release", checklist: [
    "Approved room / use / dimensional matrix released",
    "Stairs, corridors, ramps and accessibility reviewed",
    "Exit strategy / travel route / egress matrix released",
    "Lighting, ventilation and sanitation reviewed",
    "Fire compartment / shaft / service coordination reviewed",
    "Controlled drawing revision issued for construction",
  ]},
  { gateId: "STR-04", phase: "B · Design Release", title: "Structural Design Basis, Form 1 & Structural Drawings", checklist: [
    "Form 1 Structural Design Basis Report completed",
    "Geo-technical basis and founding assumptions accepted",
    "Design loads / material grades / seismic / wind basis recorded by RSE",
    "Controlled structural drawing register released",
    "Critical project-specific acceptance criteria / ITP references released",
    "Required structural review / audit applicability determined",
  ]},
  { gateId: "FIR-05", phase: "B · Design Release", title: "Fire, MEP & Service Coordination", checklist: [
    "Fire NOC applicability resolved",
    "Fire / life-safety drawings released where applicable",
    "Electrical and plumbing drawings coordinated",
    "HVAC / lift / ELV requirements coordinated where applicable",
    "Structural openings, sleeves and penetrations approved",
    "Service testing / commissioning plan defined",
  ]},
  { gateId: "PER-06", phase: "C · Permission", title: "Planning Permission / Building Permit", checklist: [
    "Planning / building permit received",
    "Permit number and validity recorded",
    "Approved plan / drawing set attached",
    "Permit conditions and required NOCs logged",
    "Approved plan available in controlled project repository",
    "Permit expiry / renewal alerts configured",
  ]},
  { gateId: "COM-07", phase: "C · Permission", title: "Commencement Control — Form 2", checklist: [
    "Form 2 / applicable commencement notice completed",
    "Authority acknowledgement / submission evidence recorded where applicable",
    "Approved drawings available at site",
    "Responsible professionals confirmed current",
    "Site display / statutory information requirements completed",
    "Construction start released by CivilMind",
  ]},
  { gateId: "PRE-08", phase: "D · Construction", title: "Pre-Construction Execution Release", checklist: [
    "IFC architectural drawings released",
    "IFC structural drawings released",
    "Coordinated MEP drawings released",
    "Inspection & Test Plan / quality plan approved",
    "Safety / temporary works controls approved",
    "RFI, NCR, change and drawing revision workflow briefed",
  ]},
  { gateId: "FDN-09", phase: "D · Construction", title: "Foundation Inspection Lots", checklist: [
    "Every foundation location represented by an inspection lot",
    "Each lot references drawing revision and ITP version",
    "Pre-concealment / pre-pour evidence exists",
    "Required tests / material certificates are linked",
    "Open critical NCR / STOP-WORK has been resolved",
    "RSE/RCE release records captured as required",
  ]},
  { gateId: "PLT-10", phase: "D · Construction", title: "Plinth Statutory Hold — Form 3 + Form 9", checklist: [
    "Plinth stage reached and survey / setbacks verified",
    "Form 3 Progress Certificate completed",
    "Form 9 Structural Inspection Report completed by RSE",
    "No unauthorized deviation requiring revised approval remains",
    "Authority continuance / deemed-continuance status recorded as applicable",
    "Plinth hold formally released",
  ]},
  { gateId: "SUP-11", phase: "D · Construction", title: "Superstructure Inspection Lots", checklist: [
    "Each floor / pour / structural location has an inspection lot",
    "Lot drawing revision and location are recorded",
    "Reinforcement / formwork / embeds / MEP openings reviewed before concealment",
    "Concrete / material tests linked to the exact lot",
    "Curing / post-pour defects / NCR disposition recorded",
    "No lot is released while a blocking control is open",
  ]},
  { gateId: "LST-12", phase: "D · Construction", title: "Last Storey Statutory Hold — Form 4 + Form 9", checklist: [
    "Last-storey structural stage inspection completed",
    "Form 4 Progress Certificate completed",
    "Form 9 Structural Inspection Report completed",
    "Roof / tank / equipment structural loads checked against design",
    "No unresolved structural deviation or critical NCR remains",
    "Last-storey hold formally released",
  ]},
  { gateId: "ARC-13", phase: "E · Completion", title: "Envelope, Interiors, MEP & Egress Completion", checklist: [
    "Waterproofing / envelope lots tested before concealment",
    "MEP concealed service evidence and test records complete",
    "Fire routes / stairs / exits unobstructed and match approved design",
    "No structural member altered by interiors / services",
    "Material approvals / warranties / traceability recorded",
    "Open defects / NCRs affecting completion are closed",
  ]},
  { gateId: "TST-14", phase: "E · Completion", title: "Final Testing & Commissioning", checklist: [
    "Electrical testing and earthing records complete",
    "Water supply / drainage / pumps tested",
    "Fire systems tested where applicable",
    "HVAC / lift / emergency systems tested where applicable",
    "Failed tests have NCR disposition and retest evidence",
    "Commissioning records accepted by responsible professionals",
  ]},
  { gateId: "ASB-15", phase: "E · Completion", title: "As-Built & Completion Dossier — Forms 5–10 as Applicable", checklist: [
    "Architectural / structural / MEP / fire as-built drawings complete",
    "Form 5 Completion Report completed as applicable",
    "Forms 6, 7 and 8 completed by applicable registered professionals",
    "Form 10 Technical Audit Report completed where applicable",
    "Test / commissioning / warranty / NOC dossier indexed",
    "Authority completion submission package complete",
  ]},
  { gateId: "OCC-16", phase: "F · Occupancy", title: "Completion / Occupancy Approval", checklist: [
    "Applicable completion / occupancy route confirmed from project classification",
    "Authority approval / certificate obtained where applicable",
    "Approved use matches proposed use",
    "Life-safety / service conditions attached to approval are closed",
    "No material post-completion deviation exists",
    "CivilMind possession release condition satisfied",
  ]},
  { gateId: "HOV-17", phase: "F · Occupancy", title: "Handover & O&M", checklist: [
    "Final approval / sanctioned plans included",
    "As-built drawings and test records included",
    "Warranties / O&M manuals / maintenance schedules issued",
    "Emergency procedures and vendor contacts issued",
    "Client / facility team training completed where applicable",
    "Signed handover receipt and post-occupancy review plan recorded",
  ]},
];